# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f84b224b2364bb8dadf10e0135271ab64c03df4c680f8634a7aa024ed4c180f0a7bed9fef1368be7444499d302227cb945f9a24cedf00ac2ef00349bf798571d

test:
  secret_key_base: 869da40e98962f15e681c9fd135acf493ef48a1fdbf468b61523397284b7bc4fbd85a175f02b6c634e0835a73fb626eb8572a0ab184efc68a1cc2b7a338a9efc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
